### PR TITLE
Add CSS for pandas dataframes and different styling of input/output cells

### LINKED ISSUE #3: Style output cells differently
This is a great project which I plan to use heavily. One little defect is bothering me. The appearance of input and output cells are identical making reading hard. (See pic of the included example below) 
image

Is there a way (such as using the preamble processor) to contrast their appearance? A subtle highlight or removal of the background gray box would help.

### PR DESCRIPTION
**Pull request by maxalbert**
What it says on the tin: this PR adds two CSS files: one for prettier display of pandas dataframes, and another one to apply different background colours to input and output cells (which properly fixes #3). Feel free to tweak the background colour of input cells if you prefer a different one.

---

**Before:**
Screen Shot 2020-02-19 at 23 31 07

---
**After:**
Screen Shot 2020-02-19 at 23 31 34

### CODE REVIEW

**Comment by maxalbert** [comment]
Sure! When you say "option flags", do you mean an enable/disable flag, or do you want options to tweak certain individual values (e.g. some key colours)? I assume the former, just wanted to check.

What should these options look like? I could imagine something simple like this:
```
  - mknotebooks:
      enable-jupyter-cell-styling: true
      enable-pandas-dataframe-styling: true
```
Or if we wanted to give the user the option to choose particular colours for the input/output cells:
```
  - mknotebooks:
      jupyter-cell-styling: true
        enabled: true
        input-cell-bg-color: #3333aa11
        output-cell-bg-color: #ececec80
      enable-pandas-dataframe-styling: true
```
Thoughts? And/or suggestions for different names?

**Comment by greenape** [comment]
I think the former suffices, maybe:

```yaml
- mknotebooks:
      enable-default-jupyter-cell-styling: true
      enable-default-pandas-dataframe-styling: true
```
?

**Comment by maxalbert** [comment]
Great, thanks. I've added the options you suggested and also added info about them in the README.

I realise that some existing options (`allow_errors`, `write_markdown`) use underscores whereas the new ones use dashes. Should this be unified, and if so which do you prefer?

**Comment by greenape** [comment]
Harmonious option names good, let's stick with underscores to avoid breaking existing config files.

**Comment by maxalbert** [comment]
Ok, I have replaced dashes with underscores in the new option names. 👍 

FYI, I also sneaked in a commit to give the variable for the exporter config a more explicit name because when reading the code I kept confusing it with the config for the mknotebooks plugin itself. Hope that's ok, but feel free to revert it if you con't like it, of course.

**Pull request merged**
